"""Pydantic schemas for API request/response models."""

from .common import (
    ErrorResponse,
    HealthResponse,
    IdempotencyHeader,
    PaginatedResponse,
    PaginationParams,
    ValidationErrorResponse,
)
from .security_scan import (
    ScanCleanupRequest,
    ScanCleanupResponse,
    ScanComparisonRequest,
    ScanComparisonResponse,
    ScanProgressUpdate,
    SecurityScanCreate,
    SecurityScanFilter,
    SecurityScanListResponse,
    SecurityScanResponse,
    SecurityScanStatistics,
    SecurityScanUpdate,
)
from .user import (
    UserBase,
    UserCreate,
    UserCreateResponse,
    UserListResponse,
    UserResponse,
    UserUpdate,
    UserUpdatePassword,
)
from .vulnerability_finding import (
    BulkUpdateRequest,
    BulkUpdateResponse,
    FindingTrendRequest,
    FindingTrendResponse,
    VulnerabilityFindingCreate,
    VulnerabilityFindingFilter,
    VulnerabilityFindingListResponse,
    VulnerabilityFindingResponse,
    VulnerabilityFindingStatistics,
    VulnerabilityFindingUpdate,
)
from .vulnerability_taxonomy import (
    DefaultTaxonomiesRequest,
    DefaultTaxonomiesResponse,
    TaxonomyRecommendationRequest,
    TaxonomyRecommendationResponse,
    VulnerabilityTaxonomyCreate,
    VulnerabilityTaxonomyFilter,
    VulnerabilityTaxonomyListResponse,
    VulnerabilityTaxonomyResponse,
    VulnerabilityTaxonomyStatistics,
    VulnerabilityTaxonomyUpdate,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserCreateResponse",
    "UserResponse",
    "UserUpdate",
    "UserUpdatePassword",
    "UserListResponse",
    # Common schemas
    "ErrorResponse",
    "ValidationErrorResponse",
    "HealthResponse",
    "PaginatedResponse",
    "PaginationParams",
    "IdempotencyHeader",
    # Vulnerability Management schemas
    "VulnerabilityTaxonomyCreate",
    "VulnerabilityTaxonomyUpdate",
    "VulnerabilityTaxonomyResponse",
    "VulnerabilityTaxonomyListResponse",
    "VulnerabilityTaxonomyStatistics",
    "VulnerabilityTaxonomyFilter",
    "DefaultTaxonomiesRequest",
    "DefaultTaxonomiesResponse",
    "TaxonomyRecommendationRequest",
    "TaxonomyRecommendationResponse",
    "VulnerabilityFindingCreate",
    "VulnerabilityFindingUpdate",
    "VulnerabilityFindingResponse",
    "VulnerabilityFindingListResponse",
    "VulnerabilityFindingStatistics",
    "VulnerabilityFindingFilter",
    "BulkUpdateRequest",
    "BulkUpdateResponse",
    "FindingTrendRequest",
    "FindingTrendResponse",
    "SecurityScanCreate",
    "SecurityScanUpdate",
    "SecurityScanResponse",
    "SecurityScanListResponse",
    "SecurityScanStatistics",
    "SecurityScanFilter",
    "ScanProgressUpdate",
    "ScanComparisonRequest",
    "ScanComparisonResponse",
    "ScanCleanupRequest",
    "ScanCleanupResponse",
]
