"""Pydantic schemas for API request/response models."""

from .common import (
    ErrorResponse,
    HealthResponse,
    IdempotencyHeader,
    PaginatedResponse,
    PaginationParams,
    ValidationErrorResponse,
)
from .scan import (
    ScanCreate,
    ScanExecutionRequest,
    ScanExecutionResponse,
    ScanFilterRequest,
    ScanFindingCreate,
    ScanFindingListResponse,
    ScanFindingResponse,
    ScanFindingUpdate,
    ScanListResponse,
    ScanReportCreate,
    ScanReportResponse,
    ScanResponse,
    ScanStatsResponse,
    ScanUpdate,
)
from .security_scan import (
    ScanCleanupRequest,
    ScanCleanupResponse,
    ScanComparisonRequest,
    ScanComparisonResponse,
    ScanProgressUpdate,
    SecurityScanCreate,
    SecurityScanFilter,
    SecurityScanListResponse,
    SecurityScanResponse,
    SecurityScanStatistics,
    SecurityScanUpdate,
)
from .task import (
    TaskBulkActionRequest,
    TaskBulkActionResponse,
    TaskCreate,
    TaskExecutionRequest,
    TaskExecutionResponse,
    TaskListResponse,
    TaskResponse,
    TaskResultCreate,
    TaskResultListResponse,
    TaskResultResponse,
    TaskRetryRequest,
    TaskStatsResponse,
    TaskStatusUpdate,
    TaskUpdate,
)
from .user import (
    UserBase,
    UserCreate,
    UserCreateResponse,
    UserListResponse,
    UserResponse,
    UserUpdate,
    UserUpdatePassword,
)
from .vulnerability_finding import (
    BulkUpdateRequest,
    BulkUpdateResponse,
    FindingTrendRequest,
    FindingTrendResponse,
    VulnerabilityFindingCreate,
    VulnerabilityFindingFilter,
    VulnerabilityFindingListResponse,
    VulnerabilityFindingResponse,
    VulnerabilityFindingStatistics,
    VulnerabilityFindingUpdate,
)
from .vulnerability_taxonomy import (
    DefaultTaxonomiesRequest,
    DefaultTaxonomiesResponse,
    TaxonomyRecommendationRequest,
    TaxonomyRecommendationResponse,
    VulnerabilityTaxonomyCreate,
    VulnerabilityTaxonomyFilter,
    VulnerabilityTaxonomyListResponse,
    VulnerabilityTaxonomyResponse,
    VulnerabilityTaxonomyStatistics,
    VulnerabilityTaxonomyUpdate,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserCreateResponse",
    "UserResponse",
    "UserUpdate",
    "UserUpdatePassword",
    "UserListResponse",
    # Common schemas
    "ErrorResponse",
    "ValidationErrorResponse",
    "HealthResponse",
    "PaginatedResponse",
    "PaginationParams",
    "IdempotencyHeader",
    # Task schemas
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "TaskExecutionRequest",
    "TaskExecutionResponse",
    "TaskStatusUpdate",
    "TaskResultCreate",
    "TaskResultResponse",
    "TaskResultListResponse",
    "TaskStatsResponse",
    "TaskRetryRequest",
    "TaskBulkActionRequest",
    "TaskBulkActionResponse",
    # Scan schemas
    "ScanCreate",
    "ScanUpdate",
    "ScanResponse",
    "ScanListResponse",
    "ScanExecutionRequest",
    "ScanExecutionResponse",
    "ScanFindingCreate",
    "ScanFindingUpdate",
    "ScanFindingResponse",
    "ScanFindingListResponse",
    "ScanReportCreate",
    "ScanReportResponse",
    "ScanStatsResponse",
    "ScanFilterRequest",
    # Vulnerability Management schemas
    "VulnerabilityTaxonomyCreate",
    "VulnerabilityTaxonomyUpdate",
    "VulnerabilityTaxonomyResponse",
    "VulnerabilityTaxonomyListResponse",
    "VulnerabilityTaxonomyStatistics",
    "VulnerabilityTaxonomyFilter",
    "DefaultTaxonomiesRequest",
    "DefaultTaxonomiesResponse",
    "TaxonomyRecommendationRequest",
    "TaxonomyRecommendationResponse",
    "VulnerabilityFindingCreate",
    "VulnerabilityFindingUpdate",
    "VulnerabilityFindingResponse",
    "VulnerabilityFindingListResponse",
    "VulnerabilityFindingStatistics",
    "VulnerabilityFindingFilter",
    "BulkUpdateRequest",
    "BulkUpdateResponse",
    "FindingTrendRequest",
    "FindingTrendResponse",
    "SecurityScanCreate",
    "SecurityScanUpdate",
    "SecurityScanResponse",
    "SecurityScanListResponse",
    "SecurityScanStatistics",
    "SecurityScanFilter",
    "ScanProgressUpdate",
    "ScanComparisonRequest",
    "ScanComparisonResponse",
    "ScanCleanupRequest",
    "ScanCleanupResponse",
]
