@startuml
!define RECTANGLE class
skinparam linetype ortho
skinparam class {
  BackgroundColor<<critical>> LightPink
  BackgroundColor<<important>> LightOrange
  BackgroundColor<<medium>> LightBlue
  BackgroundColor<<low>> LightGreen
}
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFADevice as "MFADevice" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFABackupCode as "MFABackupCode" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAChallenge as "MFAChallenge" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAPolicy as "MFAPolicy" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_MFAEvent as "MFAEvent" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_UserRole as "UserRole" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Permission as "Permission" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_Role as "Role" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthApplication as "OAuthApplication" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthAccessToken as "OAuthAccessToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthRefreshToken as "OAuthRefreshToken" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthAuthorizationCode as "OAuthAuthorizationCode" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
class model_OAuthScope as "OAuthScope" <<medium>>
@enduml
