"""Add last_login_at and last_login_ip fields to User model.

Revision ID: 41eb10f48a60
Revises: 0d9d1d5fbe10
Create Date: 2025-07-25 16:03:53.461624

"""

from typing import Sequence, Union

import sqlalchemy as sa

import alembic.op as op

# revision identifiers, used by Alembic.
revision: str = "41eb10f48a60"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "0d9d1d5fbe10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether the user email has been verified",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the user was verified",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of the user's last successful login",
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_login_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address of the user's last successful login",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login_ip")
    op.drop_column("user", "last_login_at")
    op.drop_column("user", "verified_at")
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
